version: '3.7'

services:
  web:
    build: .
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - DB_USER=hello_flask
      - DB_PASS=hello_flask
      - DB_NAME=hello_flask_dev
    ports:
      - "5432:5432"

volumes:
  postgres_data: